### ISSUE TITLE
hello, there is no effect , run your demo only 

### ISSUE THREAD

**Issue by twangithub** [joerogers/AndroidJUnitParams#1]
![image](https://github.com/joerogers/AndroidJUnitParams/assets/4607600/d1db036d-622f-41ef-8c41-dbfcf5e7a1b4)

**Comment by joerogers** [comment]
Run the test at the class level (Ie at ExampleInstrumentedTest). I updated the readme to reflect this.  This is because the lower level tests are actually multiple tests.
